
CREATE TABLE UserInfo(
	UserId VARCHAR(20) NOT NULL,
	UserName VARCHAR(100) NOT NULL,
	UserEmailId VARCHAR(100) NULL,
	Role VARCHAR(500) NULL,
	PRIMARY KEY (UserId)
);

CREATE TABLE AuthorizationInfo(
	UserId VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	lastLoginTimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (UserId),
	FOREIGN KEY (UserId) REFERENCES UserInfo(UserId)
);

CREATE TABLE LeaveInfo(
	LeaveId BIGINT NOT NULL AUTO_INCREMENT,
	UserId VARCHAR(20) NOT NULL,
	LeaveType VARCHAR(20) NOT NULL,
	NoOfDays VARCHAR(20) NOT NULL,
	LeaveOnDate DATE NOT NULL,
	leaveAppliedTimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (LeaveId),
	FOREIGN KEY (UserId) REFERENCES UserInfo(UserId)
);

CREATE TABLE ApprovalInfo(
    ApprovalId BIGINT NOT NULL AUTO_INCREMENT,
	UserId VARCHAR(30) NULL,
	LeaveId BIGINT NOT NULL,
	ApprovalStatus VARCHAR(50) NULL,
	ApprovedTimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ApprovalId),
	FOREIGN KEY (LeaveId) REFERENCES LeaveInfo(LeaveId)
);